version: '3.8'

volumes:
  freelancer_service_volume:

services:

  freelancer-service:
    working_dir: /freelancer_service_volume
    entrypoint: /freelancer_service_volume/cluster/dev-entrypoint.sh
    build:
      context: .
      dockerfile: ./cluster/dev.dockerfile
    volumes:
      - freelancer_service_volume:/freelancer_service_volume
      - ./.npmrc:/adapter_service_volume/.npmrc
    ports:
      - 9090:80
    networks:
      - juapp_dev
    environment:
      NODE_ENV: development
      PORT: 80

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    freelancer-service:
      alpha: "."
      beta: "volume://freelancer_service_volume"
      mode: "two-way-resolved"
      ignore:
        paths:
          - "node_modules"

networks:
  juapp_dev:
    external:
      name: juapp_dev
